version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-py36
      - test-py35
      - test-py34
jobs:
  test-py36: &test-template
    docker:
      - image: circleci/python:3.6
    environment:
      PY_FACTOR: py36
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
          - v2-dependencies-
      - run:
          name: run tox
          command: |
            pip install --user tox
            export TOXENV=$(~/.local/bin/tox --listenvs | grep "^${PY_FACTOR}-" | tr '\n' ',')
            ~/.local/bin/tox
      - save_cache:
          paths:
            - ~/.local
            - ./.tox
          key: v2-dependencies-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
  test-py35:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
    environment:
      PY_FACTOR: py35
  test-py34:
    <<: *test-template
    docker:
      - image: circleci/python:3.4
    environment:
      PY_FACTOR: py34
